#!/usr/bin/env python3
"""Convert Lucide SVG icons (ISC license) into a WPF ResourceDictionary of Geometry
resources (src/ProjectBrowserPlus/UI/Icons.xaml) and render ribbon PNGs (16/32 px).

Usage: python3 tools/gen_icons.py <lucide-static/icons dir>
"""
import re, sys, os, subprocess, xml.etree.ElementTree as ET

ICONS = """folder folder-open eye layers layers-2 file-text table table-2 list book-open box package
boxes link link-2 rows-3 search x refresh-cw settings star star-off chevron-right chevron-down
chevrons-down-up chevrons-up-down plus pencil trash-2 copy external-link filter arrow-down-a-z
arrow-up-z-a arrow-down-0-1 check square-check square hash text-cursor-input image pin list-tree
layout-grid sheet scroll-text book-marked ellipsis ellipsis-vertical history heart sparkles wand
paintbrush locate crosshair home target triangle-alert circle-alert replace regex save undo-2
check-check list-checks panels-top-left languages clipboard-copy table-properties sliders-horizontal
files file-plus file-x eye-off info move panel-left arrow-right arrow-left upload download
layout-dashboard map-pin land-plot ruler group ungroup component blocks library-big scan-eye view
frame square-dashed grid-2x2 image-off zoom-in loader circle-x badge-check bookmark bookmark-check
pin-off lock unlock tags tag calendar-days user file-search funnel type case-sensitive text
folder-tree square-pen file-pen file-symlink file-stack file-check layers-3 columns-3 database cuboid
shapes mountain""".split()

RIBBON = {  # png name -> icon name
    "browser": "list-tree", "settings": "settings", "about": "info", "families": "package",
}

NS = "{http://www.w3.org/2000/svg}"

def f(v):
    s = ("%.3f" % float(v)).rstrip("0").rstrip(".")
    return s if s else "0"

def rect(a):
    x, y, w, h = [float(a.get(k, 0)) for k in ("x", "y", "width", "height")]
    rx = float(a.get("rx", 0) or 0); ry = float(a.get("ry", rx) or rx)
    if rx <= 0:
        return f"M{f(x)},{f(y)} H{f(x+w)} V{f(y+h)} H{f(x)} Z"
    return (f"M{f(x+rx)},{f(y)} H{f(x+w-rx)} A{f(rx)},{f(ry)} 0 0 1 {f(x+w)},{f(y+ry)} V{f(y+h-ry)} "
            f"A{f(rx)},{f(ry)} 0 0 1 {f(x+w-rx)},{f(y+h)} H{f(x+rx)} A{f(rx)},{f(ry)} 0 0 1 {f(x)},{f(y+h-ry)} "
            f"V{f(y+ry)} A{f(rx)},{f(ry)} 0 0 1 {f(x+rx)},{f(y)} Z")

def circle(a):
    cx, cy, r = float(a["cx"]), float(a["cy"]), float(a["r"])
    return f"M{f(cx-r)},{f(cy)} A{f(r)},{f(r)} 0 1 0 {f(cx+r)},{f(cy)} A{f(r)},{f(r)} 0 1 0 {f(cx-r)},{f(cy)} Z"

def ellipse(a):
    cx, cy, rx, ry = float(a["cx"]), float(a["cy"]), float(a["rx"]), float(a["ry"])
    return f"M{f(cx-rx)},{f(cy)} A{f(rx)},{f(ry)} 0 1 0 {f(cx+rx)},{f(cy)} A{f(rx)},{f(ry)} 0 1 0 {f(cx-rx)},{f(cy)} Z"

def line(a):
    return f"M{f(a['x1'])},{f(a['y1'])} L{f(a['x2'])},{f(a['y2'])}"

def poly(a, close):
    pts = re.findall(r"-?[\d.]+", a["points"])
    pairs = [(pts[i], pts[i+1]) for i in range(0, len(pts), 2)]
    s = "M" + " L".join(f"{f(x)},{f(y)}" for x, y in pairs)
    return s + (" Z" if close else "")

def convert(path):
    root = ET.parse(path).getroot()
    parts = []
    for el in root.iter():
        t = el.tag.replace(NS, "")
        a = el.attrib
        if t == "path": parts.append(a["d"])
        elif t == "rect": parts.append(rect(a))
        elif t == "circle": parts.append(circle(a))
        elif t == "ellipse": parts.append(ellipse(a))
        elif t == "line": parts.append(line(a))
        elif t == "polyline": parts.append(poly(a, False))
        elif t == "polygon": parts.append(poly(a, True))
    return " ".join(parts)

def main():
    src = sys.argv[1]
    here = os.path.dirname(os.path.abspath(__file__))
    out_xaml = os.path.join(here, "..", "src", "ProjectBrowserPlus", "UI", "Icons.xaml")
    out_png = os.path.join(here, "..", "src", "ProjectBrowserPlus", "Resources", "Ribbon")
    os.makedirs(out_png, exist_ok=True)
    lines = ['<!-- GENERATED by tools/gen_icons.py from Lucide icons (https://lucide.dev, ISC license). Do not edit. -->',
             '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
             '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">']
    for name in ICONS:
        d = convert(os.path.join(src, name + ".svg"))
        lines.append(f'  <Geometry x:Key="ic.{name}">{d}</Geometry>')
    lines.append("</ResourceDictionary>")
    with open(out_xaml, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", out_xaml, len(ICONS), "icons")
    for png, icon in RIBBON.items():
        svg = open(os.path.join(src, icon + ".svg"), encoding="utf-8").read()
        svg = svg.replace('stroke="currentColor"', 'stroke="#2B3A4A"')
        tmp = os.path.join(out_png, "_tmp.svg")
        open(tmp, "w", encoding="utf-8").write(svg)
        for size in (16, 32):
            subprocess.check_call(["rsvg-convert", "-w", str(size), "-h", str(size), "-o",
                                   os.path.join(out_png, f"{png}{size}.png"), tmp])
        os.remove(tmp)
    print("wrote ribbon pngs")

if __name__ == "__main__":
    main()
