using System.Collections.Generic;

namespace ProjectBrowserPlus.Core
{
    /// <summary>Tiny localization table (ru / en). Unknown keys fall back to the key itself.</summary>
    public static class L
    {
        private static Dictionary<string, string> _ru, _en;

        public static string T(string key)
        {
            if (key == null) return "";
            var lang = Settings.Current.Language;
            var d = lang == "en" ? En : Ru;
            if (d.TryGetValue(key, out var s)) return s;
            if (lang == "en" && Ru.TryGetValue(key, out s)) return s;
            return key;
        }

        private static Dictionary<string, string> Ru => _ru ?? (_ru = new Dictionary<string, string>
        {
            ["app.title"] = "Диспетчер проекта+",
            ["family.doc"] = "семейство",
            ["empty.text"] = "Нет данных.\nОткройте проект или нажмите «Обновить».",
            ["status.loading"] = "Загрузка…",
            ["status.noDocument"] = "Нет открытого документа",
            ["status.count"] = "Элементов: {0}",
            ["status.filtered"] = "Показано: {0} из {1}",
            ["status.selected"] = "Выбрано: {0}",
            ["preview.none"] = "Выберите элемент, чтобы увидеть превью",
            ["preview.generate"] = "Создать превью",
            ["preview.regenerate"] = "Обновить превью (рендер вида)",
            ["draft.count"] = "Черновик: изменений — {0}",
            ["draft.apply"] = "Применить",
            ["draft.discard"] = "Отменить",
            ["draft.tip"] = "Изменения накапливаются в черновике и применяются одной транзакцией (одно «Отменить» в Revit).",

            ["vf.FloorPlan"] = "Планы этажей", ["vf.CeilingPlan"] = "Планы потолков", ["vf.StructuralPlan"] = "Планы несущих конструкций", ["vf.AreaPlan"] = "Планы зон",
            ["vf.Elevation"] = "Фасады", ["vf.Section"] = "Разрезы", ["vf.Detail"] = "Фрагменты", ["vf.ThreeDimensional"] = "3D-виды", ["vf.Drafting"] = "Чертёжные виды",
            ["vf.Legend"] = "Легенды", ["vf.Schedule"] = "Спецификации", ["vf.Sheet"] = "Листы", ["vf.Walkthrough"] = "Обходы", ["vf.ImageView"] = "Визуализации",
            ["vf.GraphicalColumnSchedule"] = "Ведомости колонн", ["vf.PanelSchedule"] = "Панельные спецификации", ["vf.CostReport"] = "Отчёты", ["vf.LoadsReport"] = "Отчёты о нагрузках", ["vf.PressureLossReport"] = "Отчёты о потерях давления",
            // tabs
            ["tab.all"] = "Всё (как в стандартном диспетчере)",
            ["tab.views"] = "Виды",
            ["tab.sheets"] = "Листы",
            ["tab.schedules"] = "Спецификации",
            ["tab.legends"] = "Легенды",
            ["tab.families"] = "Семейства",
            ["tab.groups"] = "Группы",
            ["tab.links"] = "Связи",
            ["tab.levels"] = "Уровни",
            ["tab.favorites"] = "Избранное и недавние",
            ["search.hint.all"] = "Найти в проекте…  (id:123, * — избранное)",
            ["search.hint.views"] = "Найти вид… (имя, лист, шаблон, уровень)",
            ["search.hint.sheets"] = "Найти лист… (номер, имя, ревизия)",
            ["search.hint.schedules"] = "Найти спецификацию…",
            ["search.hint.legends"] = "Найти легенду…",
            ["search.hint.families"] = "Найти семейство или типоразмер…",
            ["search.hint.groups"] = "Найти группу…",
            ["search.hint.links"] = "Найти связь…",
            ["search.hint.levels"] = "Найти уровень…",
            ["search.hint.favorites"] = "Найти в избранном…",

            // toolbar tips
            ["tip.goCurrent"] = "Показать активный вид в дереве",
            ["tip.preview"] = "Панель превью",
            ["tip.refresh"] = "Обновить (F5)",
            ["tip.settings"] = "Настройки",
            ["tip.filters"] = "Быстрые фильтры",
            ["tip.groupBy"] = "Группировка",
            ["tip.sort"] = "Сортировка",
            ["tip.expandAll"] = "Развернуть всё",
            ["tip.collapseAll"] = "Свернуть всё",
            ["tip.create"] = "Создать…",
            ["tip.tools"] = "Инструменты",

            // grouping
            ["group.std"] = "Как в Revit (организация диспетчера)",
            ["group.none"] = "Без группировки",
            ["group.viewtype"] = "По типу вида",
            ["group.viewfamily"] = "По типу вида и типоразмеру",
            ["group.level"] = "По уровню",
            ["group.template"] = "По шаблону вида",
            ["group.sheet"] = "По размещению на листах",
            ["group.discipline"] = "По дисциплине",
            ["group.phase"] = "По стадии",
            ["group.scale"] = "По масштабу",
            ["group.workset"] = "По рабочему набору",
            ["group.prefix"] = "По префиксу имени",
            ["group.sheetPrefix"] = "По префиксу номера",
            ["group.titleblock"] = "По основной надписи",
            ["group.revision"] = "По текущей ревизии",
            ["group.issueDate"] = "По дате выпуска",
            ["group.drawnBy"] = "По исполнителю (Drawn By)",
            ["group.category"] = "По категориям",
            ["group.familyKind"] = "Загружаемые / системные / в контексте",
            ["group.categoryType"] = "Модель / аннотации",
            ["group.flatFamilies"] = "Плоский список семейств",
            ["group.flatTypes"] = "Плоский список типоразмеров",
            ["group.scheduleKind"] = "По виду спецификации",
            ["group.groupKind"] = "Модельные / детализации",
            ["group.linkKind"] = "По типу связи",
            ["group.linkStatus"] = "По статусу",
            ["group.noLevel"] = "Без уровня",
            ["group.noTemplate"] = "Без шаблона",
            ["group.onSheet"] = "На листе",
            ["group.notOnSheet"] = "Не на листах",
            ["group.noTitleblock"] = "Без основной надписи",
            ["group.noRevision"] = "Без ревизии",

            // filters
            ["filter.notOnSheet"] = "Не размещённые на листах",
            ["filter.onSheet"] = "Размещённые на листах",
            ["filter.open"] = "Открытые (вкладки)",
            ["filter.noTemplate"] = "Без шаблона вида",
            ["filter.dependent"] = "Зависимые виды",
            ["filter.fav"] = "Только избранное",
            ["filter.empty"] = "Пустые листы",
            ["filter.placeholder"] = "Листы-заполнители",
            ["filter.unused"] = "Неиспользуемые",
            ["filter.used"] = "Используемые",
            ["filter.loadable"] = "Загружаемые семейства",
            ["filter.system"] = "Системные семейства",
            ["filter.inplace"] = "Семейства в контексте",
            ["filter.problem"] = "Проблемные (не найдено / выгружено)",
            ["filter.noViews"] = "Уровни без видов",

            // sort
            ["sort.nameAsc"] = "По имени А → Я",
            ["sort.nameDesc"] = "По имени Я → А",
            ["sort.numberAsc"] = "По номеру / значению ↑",
            ["sort.numberDesc"] = "По номеру / значению ↓",
            ["sort.id"] = "По Id (порядок создания)",

            // badges & tooltips
            ["badge.sheet"] = "лист",
            ["badge.dependent"] = "зависимый",
            ["badge.views"] = "видов",
            ["badge.rev"] = "рев.",
            ["badge.placeholder"] = "заполнитель",
            ["badge.sheetsCount"] = "лист(ов)",
            ["badge.unused"] = "не используется",
            ["badge.inst"] = "экз.",
            ["badge.types"] = "тип.",
            ["badge.inplace"] = "в контексте",
            ["badge.nested"] = "вложенная",
            ["tip.scale"] = "Масштаб",
            ["tip.detail"] = "Детализация",
            ["tip.level"] = "Уровень",
            ["tip.template"] = "Шаблон вида",
            ["tip.sheets"] = "На листах",
            ["tip.notOnSheet"] = "Не размещён на листах",
            ["tip.discipline"] = "Дисциплина",
            ["tip.phase"] = "Стадия",
            ["tip.workset"] = "Рабочий набор",
            ["tip.note"] = "Заметка",
            ["tip.titleblock"] = "Основная надпись",
            ["tip.revision"] = "Текущая ревизия",
            ["tip.issueDate"] = "Дата выпуска",
            ["tip.drawnBy"] = "Разработал",
            ["tip.typeMark"] = "Марка типоразмера",
            ["tip.instances"] = "Экземпляров",
            ["tip.types"] = "Типоразмеров",
            ["tip.status"] = "Статус",
            ["tip.path"] = "Путь",
            ["tip.elevation"] = "Отметка",
            ["tip.views"] = "Видов",
            ["tip.buildingStory"] = "Этаж здания",

            // kinds & statuses
            ["kind.schedule"] = "Спецификация",
            ["kind.keySchedule"] = "Ключевая спецификация",
            ["kind.materialTakeoff"] = "Ведомость материалов",
            ["kind.revisionSchedule"] = "Таблица изменений",
            ["kind.panelSchedule"] = "Панельная спецификация",
            ["kind.columnSchedule"] = "Ведомость колонн",
            ["kind.loadable"] = "Загружаемые",
            ["kind.system"] = "Системные",
            ["kind.inplace"] = "В контексте",
            ["kind.modelGroup"] = "Группы модели",
            ["kind.detailGroup"] = "Группы детализации",
            ["kind.attachedDetailGroup"] = "Присоединённые группы детализации",
            ["kind.revitLink"] = "Связи Revit",
            ["kind.cadLink"] = "Связи CAD",
            ["kind.cadImport"] = "Импорт CAD",
            ["kind.image"] = "Изображения",
            ["cattype.model"] = "Модель",
            ["cattype.annotation"] = "Аннотации",
            ["cattype.analytical"] = "Аналитическая модель",
            ["cattype.internal"] = "Внутренние",
            ["status.loaded"] = "Загружена",
            ["status.unloaded"] = "Выгружена",
            ["status.notFound"] = "Не найдена",
            ["status.locallyUnloaded"] = "Выгружена локально",
            ["status.closedWorkset"] = "В закрытом рабочем наборе",
            ["fav.favorites"] = "Избранное",
            ["fav.recent"] = "Недавно открытые",
            ["fav.open"] = "Открытые вкладки",

            // menu
            ["menu.refresh"] = "Обновить",
            ["menu.open"] = "Открыть",
            ["menu.openSheet"] = "Открыть лист с видом",
            ["menu.closeTab"] = "Закрыть вкладку вида",
            ["menu.closeTabs"] = "Закрыть вкладки выбранных видов",
            ["menu.place"] = "Разместить экземпляр",
            ["menu.selectInView"] = "Выбрать экземпляры в активном виде",
            ["menu.selectInProject"] = "Выбрать все экземпляры в проекте",
            ["menu.showInstances"] = "Показать экземпляры (подсветить и приблизить)",
            ["menu.editFamily"] = "Редактировать семейство",
            ["menu.saveFamily"] = "Сохранить семейство в папку…",
            ["menu.reload"] = "Перезагрузить",
            ["menu.unload"] = "Выгрузить",
            ["menu.openFolder"] = "Открыть папку файла",
            ["menu.createPlans"] = "Создать планы по уровням…",
            ["menu.rename"] = "Переименовать",
            ["menu.batchRename"] = "Пакетное переименование…",
            ["menu.renumber"] = "Перенумеровать листы…",
            ["menu.duplicate"] = "Дублировать…",
            ["menu.applyTemplate"] = "Применить шаблон вида…",
            ["menu.removeTemplate"] = "Снять шаблон вида",
            ["menu.placeOnSheets"] = "Разместить на листах…",
            ["menu.sheetForViews"] = "Создать лист для каждого вида…",
            ["menu.setParameter"] = "Задать параметр…",
            ["menu.favorite"] = "В избранное",
            ["menu.unfavorite"] = "Убрать из избранного",
            ["menu.note"] = "Заметка…",
            ["menu.color"] = "Цветовая метка",
            ["menu.colorNone"] = "Без метки",
            ["menu.preview"] = "Превью вида",
            ["menu.copyName"] = "Копировать имя",
            ["menu.copyId"] = "Копировать Id",
            ["menu.delete"] = "Удалить",
            ["menu.collapse"] = "Свернуть",
            ["menu.expand"] = "Развернуть",
            ["menu.expandBranch"] = "Развернуть всю ветку",
            ["menu.selectChildren"] = "Выбрать все элементы папки",
            ["menu.createSheets"] = "Создать листы…",
            ["menu.selectUnused"] = "Выбрать неиспользуемые семейства",
            ["menu.selectNotOnSheet"] = "Выбрать виды не на листах",
            ["menu.closeInactive"] = "Закрыть неактивные вкладки",
            ["menu.copyList"] = "Копировать список в буфер",
            ["menu.exportCsv"] = "Экспорт списка в CSV…",
            ["menu.clearPreviewCache"] = "Очистить кэш превью",

            // dialogs
            ["btn.ok"] = "ОК", ["btn.cancel"] = "Отмена", ["btn.apply"] = "Применить", ["btn.create"] = "Создать",
            ["btn.toDraft"] = "В черновик", ["btn.selectAll"] = "Выбрать все", ["btn.selectNone"] = "Снять выбор",
            ["dlg.rename"] = "Пакетное переименование",
            ["dlg.renumber"] = "Перенумерация листов",
            ["dlg.duplicate"] = "Дублирование видов",
            ["dlg.createSheets"] = "Создать листы",
            ["dlg.createViews"] = "Создать планы по уровням",
            ["dlg.setParameter"] = "Задать параметр",
            ["dlg.settings"] = "Настройки Project Browser+",
            ["dlg.note"] = "Заметка (хранится локально, модель не меняется)",
            ["dlg.pickTemplate"] = "Выберите шаблон вида",
            ["dlg.pickSheets"] = "Выберите листы",
            ["dlg.pickTitleblock"] = "Выберите основную надпись",
            ["dlg.noTitleblock"] = "(без основной надписи)",
            ["dlg.samePosition"] = "Ставить там же, где вид уже размещён на другом листе (иначе — в центр)",
            ["dlg.saveFamilyFolder"] = "Папка для сохранения семейства",
            ["rn.find"] = "Найти", ["rn.replace"] = "Заменить на", ["rn.regex"] = "Регулярное выражение", ["rn.case"] = "Учитывать регистр",
            ["rn.prefix"] = "Префикс", ["rn.suffix"] = "Суффикс", ["rn.numbering"] = "Нумерация", ["rn.addNumber"] = "Добавить номер",
            ["rn.start"] = "Начать с", ["rn.step"] = "Шаг", ["rn.digits"] = "Цифр", ["rn.numberPattern"] = "Шаблон",
            ["rn.patternTip"] = "{name} — имя, {n} — номер. Например: «{n}_{name}»",
            ["rn.caseMode"] = "Регистр", ["rn.caseKeep"] = "Не менять", ["rn.caseUpper"] = "ВЕРХНИЙ", ["rn.caseLower"] = "нижний", ["rn.caseTitle"] = "Каждое Слово",
            ["rn.trim"] = "Убрать двойные пробелы и пробелы по краям",
            ["rn.sheetNumbers"] = "Менять номера листов вместо имён",
            ["rn.old"] = "Было", ["rn.new"] = "Станет", ["rn.summary"] = "Изменится: {0} из {1}",
            ["rn.oldNumber"] = "Номер", ["rn.newNumber"] = "Новый номер", ["rn.sheetName"] = "Лист",
            ["rn.moveUp"] = "Выше", ["rn.moveDown"] = "Ниже", ["rn.keepOrder"] = "Порядок как в дереве",
            ["rn.keepOrderTip"] = "Листы нумеруются в том порядке, в каком они показаны (перетащите строки кнопками выше/ниже)",
            ["dup.info"] = "Видов к дублированию: {0}", ["dup.mode"] = "Способ", ["dup.plain"] = "Дублировать",
            ["dup.detailing"] = "Дублировать с деталями", ["dup.dependent"] = "Как зависимый вид",
            ["dup.copies"] = "Копий", ["dup.suffix"] = "Суффикс имени", ["dup.copyWord"] = "Копия",
            ["dup.suffixTip"] = "{n} — номер копии",
            ["cs.number"] = "Начальный номер", ["cs.count"] = "Кол-во", ["cs.name"] = "Имя листа",
            ["cs.nameTip"] = "{n} — порядковый номер, {num} — номер листа", ["cs.titleblock"] = "Основная надпись",
            ["cs.placeholder"] = "Создать листы-заполнители (без основной надписи)", ["cs.openFirst"] = "Открыть первый созданный лист",
            ["cs.defaultName"] = "Новый лист",
            ["cv.levels"] = "Уровни", ["cv.viewType"] = "Тип плана", ["cv.template"] = "Шаблон вида", ["cv.noTemplate"] = "(без шаблона)",
            ["cv.name"] = "Имя вида", ["cv.nameTip"] = "{level} — имя уровня, {type} — тип вида",
            ["sp.parameter"] = "Параметр (общий для всех выбранных)", ["sp.value"] = "Значение",
            ["sp.hint"] = "Текст — как есть; числа — в единицах проекта (например «1:100» не подходит, а «100» — да); Да/Нет — yes/no.",
            ["sp.info"] = "Элементов: {0}",
            ["st.language"] = "Язык интерфейса", ["st.languageNote"] = "Применяется после перезапуска Revit.",
            ["st.behaviour"] = "Поведение", ["st.follow"] = "Подсвечивать и раскрывать активный вид",
            ["st.singleClick"] = "Открывать вид одним кликом", ["st.closeOthers"] = "При открытии закрывать остальные вкладки",
            ["st.confirmDelete"] = "Подтверждать удаление", ["st.rememberTab"] = "Запоминать последнюю вкладку",
            ["st.display"] = "Отображение", ["st.badges"] = "Показывать бейджи (масштаб, лист, кол-во…)",
            ["st.natural"] = "Естественная сортировка (2 перед 10)", ["st.compact"] = "Компактные строки",
            ["st.sheetChildren"] = "Показывать виды внутри листов",
            ["st.families"] = "Семейства", ["st.autoPreview"] = "Автоматически показывать превью типоразмеров",
            ["st.countInstances"] = "Считать экземпляры (медленнее на больших моделях)",
            ["st.previewSize"] = "Размер превью, px", ["st.maxRecent"] = "Недавних видов",
            ["st.openFolder"] = "Папка настроек…",
            ["confirm.delete"] = "Удалить элементов: {0}?",

            // messages
            ["msg.notFound"] = "Элемент не найден",
            ["msg.notSupported"] = "Операция не поддерживается для этого элемента",
            ["msg.noPath"] = "Путь не найден",
            ["msg.cannotDuplicate"] = "вид нельзя дублировать",
            ["msg.cannotPlace"] = "нельзя разместить (уже на листе или тип вида не допускает)",
            ["msg.duplicated"] = "Создано копий: {0}",
            ["msg.deleted"] = "Удалено: {0}",
            ["msg.activeSkipped"] = "Активный вид пропущен (его нельзя удалить).",
            ["msg.templateApplied"] = "Шаблон применён к видам: {0}",
            ["msg.templateIncompatible"] = "шаблон несовместим с типом вида",
            ["msg.sheetsCreated"] = "Создано листов: {0}",
            ["msg.placed"] = "Размещено: {0}",
            ["msg.viewsCreated"] = "Создано видов: {0}",
            ["msg.noAreaScheme"] = "нет схемы зон",
            ["msg.reloaded"] = "Перезагружено",
            ["msg.unloaded"] = "Выгружено",
            ["msg.familyNotEditable"] = "Семейство нельзя редактировать",
            ["msg.familySaved"] = "Семейство сохранено в {0}",
            ["msg.paramSet"] = "Параметр задан для элементов: {0}",
            ["msg.badValue"] = "недопустимое значение",
            ["msg.noCommonParams"] = "У выбранных элементов нет общих редактируемых параметров",
            ["msg.selected"] = "Выбрано элементов: {0}",
            ["msg.selectedUnused"] = "Выбрано неиспользуемых семейств: {0}. Нажмите Del, чтобы удалить.",
            ["msg.draftApplied"] = "Применено изменений: {0}",
            ["msg.noSheets"] = "Нет листов для перенумерации",
            ["msg.exported"] = "Список экспортирован",

            // transactions (visible in Undo)
            ["tx.activateType"] = "Активировать типоразмер",
            ["tx.applyDraft"] = "Применить черновик",
            ["tx.renumber"] = "Перенумерация листов",
            ["tx.rename"] = "Переименование",
            ["tx.duplicate"] = "Дублирование видов",
            ["tx.delete"] = "Удаление",
            ["tx.template"] = "Шаблон вида",
            ["tx.createSheets"] = "Создание листов",
            ["tx.placeOnSheets"] = "Размещение на листах",
            ["tx.createViews"] = "Создание видов",
            ["tx.setParam"] = "Задать параметр",
        });

        private static Dictionary<string, string> En => _en ?? (_en = new Dictionary<string, string>
        {
            ["app.title"] = "Project Browser+",
            ["family.doc"] = "family",
            ["empty.text"] = "Nothing to show.\nOpen a project or press Refresh.",
            ["status.loading"] = "Loading…",
            ["status.noDocument"] = "No open document",
            ["status.count"] = "Items: {0}",
            ["status.filtered"] = "Shown: {0} of {1}",
            ["status.selected"] = "Selected: {0}",
            ["preview.none"] = "Select an item to see its preview",
            ["preview.generate"] = "Generate preview",
            ["preview.regenerate"] = "Re-render preview",
            ["draft.count"] = "Draft: {0} change(s)",
            ["draft.apply"] = "Apply",
            ["draft.discard"] = "Discard",
            ["draft.tip"] = "Changes are staged in a draft and applied in one transaction (one Undo in Revit).",
            ["vf.FloorPlan"] = "Floor plans", ["vf.CeilingPlan"] = "Ceiling plans", ["vf.StructuralPlan"] = "Structural plans", ["vf.AreaPlan"] = "Area plans",
            ["vf.Elevation"] = "Elevations", ["vf.Section"] = "Sections", ["vf.Detail"] = "Detail views", ["vf.ThreeDimensional"] = "3D views", ["vf.Drafting"] = "Drafting views",
            ["vf.Legend"] = "Legends", ["vf.Schedule"] = "Schedules", ["vf.Sheet"] = "Sheets", ["vf.Walkthrough"] = "Walkthroughs", ["vf.ImageView"] = "Renderings",
            ["vf.GraphicalColumnSchedule"] = "Graphical column schedules", ["vf.PanelSchedule"] = "Panel schedules", ["vf.CostReport"] = "Reports", ["vf.LoadsReport"] = "Loads reports", ["vf.PressureLossReport"] = "Pressure loss reports",
            ["tab.all"] = "Everything (classic browser)", ["tab.views"] = "Views", ["tab.sheets"] = "Sheets", ["tab.schedules"] = "Schedules",
            ["tab.legends"] = "Legends", ["tab.families"] = "Families", ["tab.groups"] = "Groups", ["tab.links"] = "Links", ["tab.levels"] = "Levels", ["tab.favorites"] = "Favorites & recent",
            ["search.hint.all"] = "Search project…  (id:123, * = favorites)", ["search.hint.views"] = "Search views… (name, sheet, template, level)",
            ["search.hint.sheets"] = "Search sheets… (number, name, revision)", ["search.hint.schedules"] = "Search schedules…", ["search.hint.legends"] = "Search legends…",
            ["search.hint.families"] = "Search families or types…", ["search.hint.groups"] = "Search groups…", ["search.hint.links"] = "Search links…", ["search.hint.levels"] = "Search levels…", ["search.hint.favorites"] = "Search favorites…",
            ["tip.goCurrent"] = "Reveal active view", ["tip.preview"] = "Preview panel", ["tip.refresh"] = "Refresh", ["tip.settings"] = "Settings", ["tip.filters"] = "Quick filters",
            ["tip.groupBy"] = "Group by", ["tip.sort"] = "Sort", ["tip.expandAll"] = "Expand all", ["tip.collapseAll"] = "Collapse all", ["tip.create"] = "Create…", ["tip.tools"] = "Tools",
            ["group.std"] = "As in Revit (browser organization)", ["group.none"] = "No grouping", ["group.viewtype"] = "By view type", ["group.viewfamily"] = "By view type and family type",
            ["group.level"] = "By level", ["group.template"] = "By view template", ["group.sheet"] = "By sheet placement", ["group.discipline"] = "By discipline", ["group.phase"] = "By phase",
            ["group.scale"] = "By scale", ["group.workset"] = "By workset", ["group.prefix"] = "By name prefix", ["group.sheetPrefix"] = "By number prefix", ["group.titleblock"] = "By title block",
            ["group.revision"] = "By current revision", ["group.issueDate"] = "By issue date", ["group.drawnBy"] = "By Drawn By", ["group.category"] = "By category",
            ["group.familyKind"] = "Loadable / system / in-place", ["group.categoryType"] = "Model / annotation", ["group.flatFamilies"] = "Flat list of families", ["group.flatTypes"] = "Flat list of types",
            ["group.scheduleKind"] = "By schedule kind", ["group.groupKind"] = "Model / detail", ["group.linkKind"] = "By link type", ["group.linkStatus"] = "By status",
            ["group.noLevel"] = "No level", ["group.noTemplate"] = "No template", ["group.onSheet"] = "On sheet", ["group.notOnSheet"] = "Not on sheets", ["group.noTitleblock"] = "No title block", ["group.noRevision"] = "No revision",
            ["filter.notOnSheet"] = "Not placed on sheets", ["filter.onSheet"] = "Placed on sheets", ["filter.open"] = "Open (tabs)", ["filter.noTemplate"] = "Without view template",
            ["filter.dependent"] = "Dependent views", ["filter.fav"] = "Favorites only", ["filter.empty"] = "Empty sheets", ["filter.placeholder"] = "Placeholder sheets", ["filter.unused"] = "Unused",
            ["filter.used"] = "Used", ["filter.loadable"] = "Loadable families", ["filter.system"] = "System families", ["filter.inplace"] = "In-place families", ["filter.problem"] = "Problems (not found / unloaded)", ["filter.noViews"] = "Levels without views",
            ["sort.nameAsc"] = "Name A → Z", ["sort.nameDesc"] = "Name Z → A", ["sort.numberAsc"] = "Number / value ↑", ["sort.numberDesc"] = "Number / value ↓", ["sort.id"] = "By Id (creation order)",
            ["badge.sheet"] = "sheet", ["badge.dependent"] = "dependent", ["badge.views"] = "views", ["badge.rev"] = "rev.", ["badge.placeholder"] = "placeholder", ["badge.sheetsCount"] = "sheet(s)",
            ["badge.unused"] = "unused", ["badge.inst"] = "inst.", ["badge.types"] = "types", ["badge.inplace"] = "in-place", ["badge.nested"] = "nested",
            ["tip.scale"] = "Scale", ["tip.detail"] = "Detail level", ["tip.level"] = "Level", ["tip.template"] = "View template", ["tip.sheets"] = "On sheets", ["tip.notOnSheet"] = "Not placed on a sheet",
            ["tip.discipline"] = "Discipline", ["tip.phase"] = "Phase", ["tip.workset"] = "Workset", ["tip.note"] = "Note", ["tip.titleblock"] = "Title block", ["tip.revision"] = "Current revision",
            ["tip.issueDate"] = "Issue date", ["tip.drawnBy"] = "Drawn by", ["tip.typeMark"] = "Type mark", ["tip.instances"] = "Instances", ["tip.types"] = "Types", ["tip.status"] = "Status", ["tip.path"] = "Path",
            ["tip.elevation"] = "Elevation", ["tip.views"] = "Views", ["tip.buildingStory"] = "Building story",
            ["kind.schedule"] = "Schedule", ["kind.keySchedule"] = "Key schedule", ["kind.materialTakeoff"] = "Material takeoff", ["kind.revisionSchedule"] = "Revision schedule",
            ["kind.panelSchedule"] = "Panel schedule", ["kind.columnSchedule"] = "Graphical column schedule", ["kind.loadable"] = "Loadable", ["kind.system"] = "System", ["kind.inplace"] = "In-place",
            ["kind.modelGroup"] = "Model groups", ["kind.detailGroup"] = "Detail groups", ["kind.attachedDetailGroup"] = "Attached detail groups", ["kind.revitLink"] = "Revit links", ["kind.cadLink"] = "CAD links", ["kind.cadImport"] = "CAD imports", ["kind.image"] = "Images",
            ["cattype.model"] = "Model", ["cattype.annotation"] = "Annotation", ["cattype.analytical"] = "Analytical", ["cattype.internal"] = "Internal",
            ["status.loaded"] = "Loaded", ["status.unloaded"] = "Unloaded", ["status.notFound"] = "Not found", ["status.locallyUnloaded"] = "Locally unloaded", ["status.closedWorkset"] = "In closed workset",
            ["fav.favorites"] = "Favorites", ["fav.recent"] = "Recently opened", ["fav.open"] = "Open tabs",
            ["menu.refresh"] = "Refresh", ["menu.open"] = "Open", ["menu.openSheet"] = "Open sheet", ["menu.closeTab"] = "Close view tab", ["menu.closeTabs"] = "Close selected view tabs",
            ["menu.place"] = "Place instance", ["menu.selectInView"] = "Select instances in active view", ["menu.selectInProject"] = "Select all instances in project", ["menu.showInstances"] = "Show instances (highlight and zoom)",
            ["menu.editFamily"] = "Edit family", ["menu.saveFamily"] = "Save family to folder…", ["menu.reload"] = "Reload", ["menu.unload"] = "Unload", ["menu.openFolder"] = "Open containing folder",
            ["menu.createPlans"] = "Create plans for levels…", ["menu.rename"] = "Rename", ["menu.batchRename"] = "Batch rename…", ["menu.renumber"] = "Renumber sheets…", ["menu.duplicate"] = "Duplicate…",
            ["menu.applyTemplate"] = "Apply view template…", ["menu.removeTemplate"] = "Remove view template", ["menu.placeOnSheets"] = "Place on sheets…", ["menu.sheetForViews"] = "Create a sheet per view…",
            ["menu.setParameter"] = "Set parameter…", ["menu.favorite"] = "Add to favorites", ["menu.unfavorite"] = "Remove from favorites", ["menu.note"] = "Note…", ["menu.color"] = "Color tag", ["menu.colorNone"] = "No tag",
            ["menu.preview"] = "View preview", ["menu.copyName"] = "Copy name", ["menu.copyId"] = "Copy Id", ["menu.delete"] = "Delete", ["menu.collapse"] = "Collapse", ["menu.expand"] = "Expand",
            ["menu.expandBranch"] = "Expand whole branch", ["menu.selectChildren"] = "Select all items in folder", ["menu.createSheets"] = "Create sheets…", ["menu.selectUnused"] = "Select unused families",
            ["menu.selectNotOnSheet"] = "Select views not on sheets", ["menu.closeInactive"] = "Close inactive tabs", ["menu.copyList"] = "Copy list to clipboard", ["menu.exportCsv"] = "Export list to CSV…", ["menu.clearPreviewCache"] = "Clear preview cache",
            ["btn.ok"] = "OK", ["btn.cancel"] = "Cancel", ["btn.apply"] = "Apply", ["btn.create"] = "Create", ["btn.toDraft"] = "To draft", ["btn.selectAll"] = "Select all", ["btn.selectNone"] = "Select none",
            ["dlg.rename"] = "Batch rename", ["dlg.renumber"] = "Renumber sheets", ["dlg.duplicate"] = "Duplicate views", ["dlg.createSheets"] = "Create sheets", ["dlg.createViews"] = "Create plans for levels",
            ["dlg.setParameter"] = "Set parameter", ["dlg.settings"] = "Project Browser+ settings", ["dlg.note"] = "Note (stored locally, the model is not modified)", ["dlg.pickTemplate"] = "Pick a view template",
            ["dlg.pickSheets"] = "Pick sheets", ["dlg.pickTitleblock"] = "Pick a title block", ["dlg.noTitleblock"] = "(no title block)",
            ["dlg.samePosition"] = "Use the position the view already has on another sheet (otherwise centre)", ["dlg.saveFamilyFolder"] = "Folder to save the family",
            ["rn.find"] = "Find", ["rn.replace"] = "Replace with", ["rn.regex"] = "Regular expression", ["rn.case"] = "Match case", ["rn.prefix"] = "Prefix", ["rn.suffix"] = "Suffix", ["rn.numbering"] = "Numbering",
            ["rn.addNumber"] = "Add number", ["rn.start"] = "Start", ["rn.step"] = "Step", ["rn.digits"] = "Digits", ["rn.numberPattern"] = "Pattern", ["rn.patternTip"] = "{name} = name, {n} = number, e.g. \"{n}_{name}\"",
            ["rn.caseMode"] = "Case", ["rn.caseKeep"] = "Keep", ["rn.caseUpper"] = "UPPER", ["rn.caseLower"] = "lower", ["rn.caseTitle"] = "Title Case", ["rn.trim"] = "Trim and collapse double spaces",
            ["rn.sheetNumbers"] = "Change sheet numbers instead of names", ["rn.old"] = "Current", ["rn.new"] = "New", ["rn.summary"] = "Will change: {0} of {1}", ["rn.oldNumber"] = "Number", ["rn.newNumber"] = "New number",
            ["rn.sheetName"] = "Sheet", ["rn.moveUp"] = "Move up", ["rn.moveDown"] = "Move down", ["rn.keepOrder"] = "Order as in tree", ["rn.keepOrderTip"] = "Sheets are numbered in the shown order (reorder with the arrows)",
            ["dup.info"] = "Views to duplicate: {0}", ["dup.mode"] = "Mode", ["dup.plain"] = "Duplicate", ["dup.detailing"] = "Duplicate with detailing", ["dup.dependent"] = "Duplicate as dependent",
            ["dup.copies"] = "Copies", ["dup.suffix"] = "Name suffix", ["dup.copyWord"] = "Copy", ["dup.suffixTip"] = "{n} = copy number",
            ["cs.number"] = "Start number", ["cs.count"] = "Count", ["cs.name"] = "Sheet name", ["cs.nameTip"] = "{n} = index, {num} = sheet number", ["cs.titleblock"] = "Title block",
            ["cs.placeholder"] = "Create placeholder sheets", ["cs.openFirst"] = "Open the first created sheet", ["cs.defaultName"] = "New sheet",
            ["cv.levels"] = "Levels", ["cv.viewType"] = "Plan type", ["cv.template"] = "View template", ["cv.noTemplate"] = "(no template)", ["cv.name"] = "View name", ["cv.nameTip"] = "{level} = level name, {type} = view type",
            ["sp.parameter"] = "Parameter (common to all selected)", ["sp.value"] = "Value", ["sp.hint"] = "Text as is; numbers in project units; Yes/No as yes/no.", ["sp.info"] = "Elements: {0}",
            ["st.language"] = "Language", ["st.languageNote"] = "Takes effect after Revit restarts.", ["st.behaviour"] = "Behaviour", ["st.follow"] = "Highlight and reveal the active view",
            ["st.singleClick"] = "Open views with a single click", ["st.closeOthers"] = "Close other tabs when opening a view", ["st.confirmDelete"] = "Confirm deletion", ["st.rememberTab"] = "Remember last tab",
            ["st.display"] = "Display", ["st.badges"] = "Show badges (scale, sheet, counts…)", ["st.natural"] = "Natural sort (2 before 10)", ["st.compact"] = "Compact rows", ["st.sheetChildren"] = "Show views under sheets",
            ["st.families"] = "Families", ["st.autoPreview"] = "Show type previews automatically", ["st.countInstances"] = "Count instances (slower on big models)", ["st.previewSize"] = "Preview size, px", ["st.maxRecent"] = "Recent views",
            ["st.openFolder"] = "Settings folder…", ["confirm.delete"] = "Delete {0} element(s)?",
            ["msg.notFound"] = "Element not found", ["msg.notSupported"] = "Not supported for this element", ["msg.noPath"] = "Path not found", ["msg.cannotDuplicate"] = "view cannot be duplicated",
            ["msg.cannotPlace"] = "cannot be placed (already on a sheet or view type not allowed)", ["msg.duplicated"] = "Copies created: {0}", ["msg.deleted"] = "Deleted: {0}", ["msg.activeSkipped"] = "Active view skipped (it cannot be deleted).",
            ["msg.templateApplied"] = "Template applied to {0} view(s)", ["msg.templateIncompatible"] = "template incompatible with view type", ["msg.sheetsCreated"] = "Sheets created: {0}", ["msg.placed"] = "Placed: {0}",
            ["msg.viewsCreated"] = "Views created: {0}", ["msg.noAreaScheme"] = "no area scheme", ["msg.reloaded"] = "Reloaded", ["msg.unloaded"] = "Unloaded", ["msg.familyNotEditable"] = "Family is not editable",
            ["msg.familySaved"] = "Family saved to {0}", ["msg.paramSet"] = "Parameter set on {0} element(s)", ["msg.badValue"] = "invalid value", ["msg.noCommonParams"] = "Selected elements share no editable parameters",
            ["msg.selected"] = "Selected: {0}", ["msg.selectedUnused"] = "Unused families selected: {0}. Press Del to delete.", ["msg.draftApplied"] = "Applied changes: {0}", ["msg.noSheets"] = "No sheets to renumber", ["msg.exported"] = "List exported",
            ["tx.activateType"] = "Activate type", ["tx.applyDraft"] = "Apply draft", ["tx.renumber"] = "Renumber sheets", ["tx.rename"] = "Rename", ["tx.duplicate"] = "Duplicate views", ["tx.delete"] = "Delete",
            ["tx.template"] = "View template", ["tx.createSheets"] = "Create sheets", ["tx.placeOnSheets"] = "Place on sheets", ["tx.createViews"] = "Create views", ["tx.setParam"] = "Set parameter",
        });
    }
}
